pipeline.batch.size: 125
pipeline.batch.delay: 50
node.name: logstash
path.config: /usr/share/logstash/pipeline/*.conf
path.data: /usr/share/logstash/data
#path.plugins: ["/usr/share/logstash/plugins"]
path.settings: /usr/share/logstash/config